// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	cart "github.com/crazyfrankie/bytedance-mall/app/frontend/biz/router/cart"
	category "github.com/crazyfrankie/bytedance-mall/app/frontend/biz/router/category"
	checkout "github.com/crazyfrankie/bytedance-mall/app/frontend/biz/router/checkout"
	home "github.com/crazyfrankie/bytedance-mall/app/frontend/biz/router/home"
	order "github.com/crazyfrankie/bytedance-mall/app/frontend/biz/router/order"
	product "github.com/crazyfrankie/bytedance-mall/app/frontend/biz/router/product"
	user "github.com/crazyfrankie/bytedance-mall/app/frontend/biz/router/user"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	order.Register(r)

	checkout.Register(r)

	cart.Register(r)

	category.Register(r)

	product.Register(r)

	home.Register(r)

	user.Register(r)
}
