// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	category "github.com/crazyfrankie/bytedance-mall/app/frontend/biz/router/category"
	home "github.com/crazyfrankie/bytedance-mall/app/frontend/biz/router/home"
	product "github.com/crazyfrankie/bytedance-mall/app/frontend/biz/router/product"
	user "github.com/crazyfrankie/bytedance-mall/app/frontend/biz/router/user"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	category.Register(r)

	product.Register(r)

	home.Register(r)

	user.Register(r)
}
